# Permalinks
permalink: /:title/
#relative_permalinks: true

# Setup
title:            rtfmp
tagline:          Read the fucking man pages 
url:              http://rtfmp.github.io
paginate:         1
baseurl:          /
author:
  name:           Benjamin Rualthanzauva
  url:            https://twitter.com/rualthanzauva
  email:          benjaminrtz@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/rtfmp/rtfmp

#Pages
pages_list:       
  Archive: '/archive'
  
